const STORE={bookings:'claraBookingsV2',blocked:'claraBlockedSlotsV2',seed:'claraSeedV2'};
const services=[
  {name:'BIAB Manicure',duration:75,price:35,note:'Natural strength & glossy finish'},
  {name:'Gel Manicure',duration:60,price:30,note:'Careful prep & flawless colour'},
  {name:'BIAB + Nail Art',duration:90,price:40,note:'Structured base & delicate art'},
  {name:'Removal',duration:30,price:10,note:'Gentle soak-off & aftercare'}
];
const weekly={2:['10:00','12:00','14:30','16:00'],3:['09:30','11:30','14:00','16:30'],4:['10:00','12:30','15:00','17:00'],5:['09:30','11:30','14:30','16:30'],6:['10:00','12:30','15:00']};
const state={service:null,date:null,time:null,lastBooking:null};
let page=0;
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateFromIso=value=>{const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)};
const formatDate=(value,options={weekday:'short',day:'numeric',month:'short'})=>dateFromIso(value).toLocaleDateString('en-GB',options);
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
function bookableDays(count=8){const days=[];const cursor=new Date();cursor.setHours(12,0,0,0);while(days.length<count){cursor.setDate(cursor.getDate()+1);if(weekly[cursor.getDay()])days.push(new Date(cursor))}return days}
function seedDemo(){if(localStorage.getItem(STORE.seed))return;const days=bookableDays();const demo=[{id:'demo-1',service:'BIAB Manicure',date:iso(days[1]),time:weekly[days[1].getDay()][1],duration:75,price:35,name:'Sophie M.',email:'sophie@example.com',phone:'07700 900321',notes:'Soft French',status:'confirmed',source:'demo',createdAt:new Date().toISOString()},{id:'demo-2',service:'Gel Manicure',date:iso(days[3]),time:weekly[days[3].getDay()][0],duration:60,price:30,name:'Mia R.',email:'mia@example.com',phone:'07700 900654',notes:'Deep berry',status:'confirmed',source:'demo',createdAt:new Date().toISOString()}];write(STORE.bookings,demo);localStorage.setItem(STORE.seed,'1')}
function unavailable(date){const bookings=read(STORE.bookings,[]).filter(b=>b.date===date&&b.status!=='cancelled').map(b=>b.time);const blocked=read(STORE.blocked,{})[date]||[];return new Set([...bookings,...blocked])}
function availableTimes(date){const d=dateFromIso(date);return (weekly[d.getDay()]||[]).filter(t=>!unavailable(date).has(t))}
function nextAvailable(){for(const d of bookableDays()){const times=availableTimes(iso(d));if(times.length)return{date:iso(d),time:times[0]}}return null}
function show(n){page=n;document.querySelectorAll('.book-page').forEach((el,i)=>el.classList.toggle('active',i===n));document.querySelectorAll('.progress-step').forEach((el,i)=>{el.classList.toggle('active',i===Math.min(n,3));el.classList.toggle('complete',i<n);el.disabled=i>n||n===4});}
function renderServices(){document.getElementById('serviceChoices').innerHTML=services.map(s=>`<button class="service-choice" data-service="${s.name}"><span class="radio"></span><span>${s.name}<small>${s.duration} mins · ${s.note}</small></span><b>${s.price===35||s.price===40?'From ':''}£${s.price}</b></button>`).join('');document.querySelectorAll('.service-choice').forEach(btn=>btn.addEventListener('click',()=>selectService(btn.dataset.service)))}
function selectService(name){state.service=services.find(s=>s.name===name);document.querySelectorAll('.service-choice').forEach(btn=>btn.classList.toggle('selected',btn.dataset.service===name));const next=document.querySelector('[data-page="0"] .next');next.disabled=false;next.textContent='Continue';}
function renderDates(){const dates=document.getElementById('dates');dates.innerHTML=bookableDays().slice(0,4).map(d=>`<button class="date" data-date="${iso(d)}"><span>${d.toLocaleDateString('en-GB',{weekday:'short'})}</span><b>${d.getDate()}</b><span>${d.toLocaleDateString('en-GB',{month:'short'})}</span></button>`).join('');dates.querySelectorAll('.date').forEach(btn=>btn.addEventListener('click',()=>selectDate(btn.dataset.date)))}
function selectDate(value){state.date=value;state.time=null;document.querySelectorAll('.date').forEach(btn=>btn.classList.toggle('selected',btn.dataset.date===value));const times=availableTimes(value);document.getElementById('slotLabel').textContent=times.length?`${times.length} appointments available on ${formatDate(value,{weekday:'long',day:'numeric',month:'long'})}`:'This day is now fully booked';document.getElementById('times').innerHTML=times.length?times.map(t=>`<button class="time" data-time="${t}">${t}</button>`).join(''):'<div class="empty-slots">Try another day—new appointments are added regularly.</div>';document.querySelectorAll('.time').forEach(btn=>btn.addEventListener('click',()=>selectTime(btn.dataset.time)));document.querySelector('[data-page="1"] .next').disabled=true;}
function selectTime(value){state.time=value;document.querySelectorAll('.time').forEach(btn=>btn.classList.toggle('selected',btn.dataset.time===value));document.querySelector('[data-page="1"] .next').disabled=false;}
function validateDetails(){const name=document.getElementById('clientName'),email=document.getElementById('clientEmail'),error=document.getElementById('formError');if(!name.value.trim()){error.textContent='Please add your name to continue.';name.focus();return false}if(!email.validity.valid||!email.value.trim()){error.textContent='Please add a valid email address.';email.focus();return false}error.textContent='';return true}
function renderSummary(){document.getElementById('summary').innerHTML=`<div class="summary-row"><span>Treatment</span><b>${state.service.name}<br>£${state.service.price}</b></div><div class="summary-row"><span>Appointment</span><b>${formatDate(state.date,{weekday:'long',day:'numeric',month:'long'})}<br>${state.time} · ${state.service.duration} mins</b></div><div class="summary-row"><span>Client</span><b>${document.getElementById('clientName').value.trim()}<br>${document.getElementById('clientEmail').value.trim()}</b></div>`}
function confirmBooking(){if(unavailable(state.date).has(state.time)){alert('That appointment has just been taken. Please choose another time.');show(1);selectDate(state.date);return}const booking={id:`clara-${Date.now()}`,service:state.service.name,date:state.date,time:state.time,duration:state.service.duration,price:state.service.price,name:document.getElementById('clientName').value.trim(),email:document.getElementById('clientEmail').value.trim(),phone:document.getElementById('clientPhone').value.trim(),instagram:document.getElementById('clientInstagram').value.trim(),notes:document.getElementById('clientNotes').value.trim(),status:'confirmed',source:'client',createdAt:new Date().toISOString()};const bookings=read(STORE.bookings,[]);bookings.push(booking);write(STORE.bookings,bookings);state.lastBooking=booking;document.getElementById('confirmText').textContent=`${booking.service} on ${formatDate(booking.date,{weekday:'long',day:'numeric',month:'long'})} at ${booking.time} is reserved. It is already visible in the owner dashboard.`;show(4);updateNextAvailable()}
function calendarStamp(date,time){return `${date.replaceAll('-','')}T${time.replace(':','')}00`}
function downloadCalendar(){const b=state.lastBooking;if(!b)return;const start=calendarStamp(b.date,b.time);const endDate=new Date(`${b.date}T${b.time}:00`);endDate.setMinutes(endDate.getMinutes()+Number(b.duration));const end=`${iso(endDate).replaceAll('-','')}T${String(endDate.getHours()).padStart(2,'0')}${String(endDate.getMinutes()).padStart(2,'0')}00`;const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Clara Studios//Booking Demo//EN','BEGIN:VEVENT',`UID:${b.id}@clarastudios.demo`,`DTSTART:${start}`,`DTEND:${end}`,`SUMMARY:${b.service} at Clara Studios`,'DESCRIPTION:Your private nail studio appointment. Demo calendar event.','LOCATION:Clara Studios - full address supplied after booking','END:VEVENT','END:VCALENDAR'].join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:'text/calendar'}));link.download='clara-studios-appointment.ics';link.click();URL.revokeObjectURL(link.href)}
function updateNextAvailable(){const next=nextAvailable();document.getElementById('nextAvailable').textContent=next?`${formatDate(next.date)} · ${next.time}`:'Join the waitlist'}
function resetFlow(){state.service=null;state.date=null;state.time=null;state.lastBooking=null;document.getElementById('detailsForm').reset();renderServices();renderDates();document.getElementById('times').innerHTML='';document.getElementById('slotLabel').textContent='Select a day to see available times';show(0)}
seedDemo();renderServices();renderDates();updateNextAvailable();
document.querySelectorAll('.next').forEach(btn=>btn.addEventListener('click',()=>{if(page===0&&!state.service)return;if(page===1&&!state.time)return;if(page===2&&!validateDetails())return;if(page===2)renderSummary();show(page+1)}));
document.querySelectorAll('.back-step').forEach(btn=>btn.addEventListener('click',()=>show(page-1)));
document.getElementById('confirmBooking').addEventListener('click',confirmBooking);document.getElementById('downloadCalendar').addEventListener('click',downloadCalendar);document.getElementById('resetBooking').addEventListener('click',resetFlow);
document.querySelectorAll('[data-pick]').forEach(link=>link.addEventListener('click',()=>selectService(link.dataset.pick)));
const menu=document.querySelector('.menu-button'),nav=document.getElementById('site-nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
window.addEventListener('storage',event=>{if([STORE.bookings,STORE.blocked].includes(event.key)){renderDates();updateNextAvailable()}});
